# -*- coding: utf-8 -*-
"""phone_number_tracker.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1DaV7CT4YMmlCcKsTicoqsbux9RB18Olz
"""

!pip install phonenumbers

import phonenumbers

from phonenumbers import timezone
from phonenumbers import geocoder

phone_number=phonenumbers.parse("+919363289459")

time_zone=timezone.time_zones_for_number(phone_number)
print(time_zone)

print("Phone Number Location")
print(geocoder.description_for_number(phone_number,"en"))

